on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:

  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Linter
        run: npm run lint

  # build:
  #   needs: [linter]
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: 'npm'
  #         node-version: 18
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Build
  #       run: npm run build
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: dist
  #         path: dist

  # test:
  #   needs: [linter, build]
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: 'npm'
  #         node-version: 18
  #     - name: Install dependencies
  #       run: npm install
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: dist
  #         path: dist
  #     - name: Test
  #       run: npm run test

  build-and-deploy:
    needs: [linter]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18 # Ajusta esto según tu versión de Node.js

      - name: Install Dependencies
        run: npm install

      - name: NPM Install Angular
        run: npm install -g @angular/cli

      - name: Build Project
        run: ng build --prod

      - name: Archive Build Output
        run: zip -r build.zip dist/

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          # key: ${{ secrets.KEY }}
          source: "build.zip"
          target: "/tmp"

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          # key: ${{ secrets.KEY }}
          script: |
            rm -rf /home/alvarosegovia/domains/ga.alvarosegovia.com/public_html/*
            unzip /tmp/build.zip -d /home/alvarosegovia/domains/ga.alvarosegovia.com/public_html
            rm /tmp/build.zip